spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/SpringBootKeycloak
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
      client :
        registration: 
          keycloak: 
              client-id : login-app
              authorization-grant-type : password
              scope : openid
        provider : 
          keycloak : 
              issuer-uri : http://localhost:8080/realms/SpringBootKeycloak
              user-name-attribute : user1